"""
Data models, enums, and protocols for the AGGRESSOR pipeline.

Defines all structured data types used throughout the mutagenesis workflow:
- Mutation type classification
- Cluster representations (standard, hydrophobic-aromatic, multi-rule)
- Position context and mutation information
- Multi-point mutation results
- Cluster evaluator protocol

References:
- Rousseau et al., J Mol Biol 2006 (gatekeeper hypothesis)
- Tartaglia et al., J Mol Biol 2008 (aggregation propensity scale)
"""
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import (
    List, Tuple, Dict, Set, Any, Optional,
    FrozenSet, Protocol, runtime_checkable, Union
)

from config import AGGREGATION_PROPENSITY


# =============================================================================
# ENUMS
# =============================================================================

class MutationType(Enum):
    """
    Classification of mutations by structural/functional context.

    Based on the gatekeeper hypothesis (Rousseau et al., 2006) and
    aggregation-prone region (APR) architecture.

    Categories:
        BETA_CORE: Within identified aggregation cluster (highest risk)
        GATEKEEPER: At cluster boundary with gatekeeper AA (disrupts β-extension)
        FLANKING: Adjacent to APR but not gatekeeper position/AA
        BOUNDARY: At APR boundary but mutation is not to gatekeeper AA
        DIRECT: User-specified position (no rule context)
        INSERTION: Amino acid insertion
        IDR_PROXIMAL: Near intrinsically disordered region (future use)
        UNKNOWN: Cannot classify position/mutation
    """
    BETA_CORE = auto()
    GATEKEEPER = auto()
    FLANKING = auto()
    BOUNDARY = auto()
    DIRECT = auto()
    INSERTION = auto()
    IDR_PROXIMAL = auto()
    UNKNOWN = auto()

    @classmethod
    def from_description(cls, description: str) -> 'MutationType':
        """
        Parse mutation type from a description string.

        Uses keyword matching to determine the mutation type from
        the formatted description strings generated by the pipeline.

        Args:
            description: Formatted mutation description string

        Returns:
            Corresponding MutationType enum value

        Examples:
            >>> MutationType.from_description("A10P | GATEKEEPER (agg_score=3)")
            <MutationType.GATEKEEPER: 2>
        """
        if 'GATEKEEPER' in description:
            return cls.GATEKEEPER
        elif 'BOUNDARY' in description:
            return cls.BOUNDARY
        elif 'FLANKING' in description:
            return cls.FLANKING
        elif 'Direct mutation' in description:
            return cls.DIRECT
        elif 'Insertion' in description:
            return cls.INSERTION
        elif 'CORE' in description:
            return cls.BETA_CORE
        elif "Rule '" in description or 'MERGED RULES' in description:
            return cls.BETA_CORE
        return cls.UNKNOWN

    def __str__(self) -> str:
        """Human-readable string representation."""
        return self.name


# =============================================================================
# PROTOCOLS
# =============================================================================

@runtime_checkable
class ClusterEvaluator(Protocol):
    """
    Protocol defining the interface for aggregation rule evaluators.

    Each evaluator implements a specific aggregation propensity rule
    (e.g., hydrophobic aliphatic clustering, aromatic stacking).

    Required Properties:
        name: Unique rule identifier string
        description: Human-readable rule description
        aggregation_score: Integer weight for this rule's contribution
        residues: Set of amino acids this rule applies to

    Required Methods:
        find_clusters: Identify clusters in a sequence region
    """

    @property
    def name(self) -> str:
        """Unique identifier for this rule evaluator."""
        ...

    @property
    def description(self) -> str:
        """Human-readable description of what this rule detects."""
        ...

    @property
    def aggregation_score(self) -> int:
        """Integer weight indicating this rule's aggregation contribution."""
        ...

    @property
    def residues(self) -> FrozenSet[str]:
        """Set of amino acid single-letter codes this rule operates on."""
        ...

    def find_clusters(
            self,
            sequence: str,
            start: int,
            stop: int
    ) -> List['Cluster']:
        """
        Find all clusters matching this rule in the given region.

        Args:
            sequence: Full protein sequence
            start: 1-indexed start position of region to analyze
            stop: 1-indexed end position of region to analyze

        Returns:
            List of Cluster objects matching this rule
        """
        ...


# =============================================================================
# CLUSTER DATA CLASSES
# =============================================================================

@dataclass(frozen=True, slots=True)
class Cluster:
    """
    Immutable representation of an aggregation-prone cluster identified by a single rule.

    Using frozen=True enables:
    - Hashability (can be used in sets, as dict keys)
    - Thread safety (no mutation possible after creation)
    - Semantic clarity (clusters are identified, not modified)

    Using slots=True reduces memory footprint by ~40% per instance compared
    to standard dataclass with __dict__.

    Attributes:
        positions: 1-indexed positions of residues in the cluster (must be sorted)
        residues: Amino acid single-letter codes at each position
        rule_name: Name of the rule that identified this cluster
        aggregation_score: Integer score indicating aggregation propensity weight

    Raises:
        ValueError: If positions and residues have different lengths,
                   if positions are empty, or if positions are not in sorted order
    """
    positions: Tuple[int, ...]
    residues: Tuple[str, ...]
    rule_name: str
    aggregation_score: int

    def __post_init__(self):
        """Validate cluster invariants after initialization."""
        if len(self.positions) != len(self.residues):
            raise ValueError(
                f"Position count ({len(self.positions)}) must match "
                f"residue count ({len(self.residues)})"
            )
        if not self.positions:
            raise ValueError("Cluster must contain at least one position")

        if any(p < 1 for p in self.positions):
            raise ValueError("Positions must be 1-indexed (≥1)")
        if list(self.positions) != sorted(self.positions):
            raise ValueError("Positions must be in sorted order")

    @property
    def size(self) -> int:
        """Number of residues in the cluster."""
        return len(self.positions)

    @property
    def span(self) -> int:
        """Sequence span from first to last position (inclusive)."""
        return max(self.positions) - min(self.positions) + 1

    @property
    def density(self) -> float:
        """
        Cluster density: occupied positions / total span.

        Higher density indicates tighter packing of aggregation-prone
        residues in the primary sequence, which correlates with
        stronger aggregation propensity.
        """
        return self.size / self.span if self.span > 0 else 0.0

    @property
    def motif(self) -> str:
        """The cluster residues concatenated as a sequence motif."""
        return ''.join(self.residues)

    @property
    def mean_propensity(self) -> float:
        """
        Average intrinsic aggregation propensity of cluster residues.

        Uses the Tartaglia et al. (2008) aggregation propensity scale.
        Higher values indicate stronger predicted aggregation tendency.
        """
        propensities = [AGGREGATION_PROPENSITY.get(aa, 0.0) for aa in self.residues]
        return sum(propensities) / len(propensities) if propensities else 0.0

    @property
    def min_position(self) -> int:
        """N-terminal boundary of the cluster."""
        return min(self.positions)

    @property
    def max_position(self) -> int:
        """C-terminal boundary of the cluster."""
        return max(self.positions)

    def overlaps_with(self, other: 'Cluster', gap_tolerance: int = 0) -> bool:
        """
        Check if this cluster overlaps with another cluster.

        Two clusters overlap if their position ranges intersect or
        are within gap_tolerance positions of each other.

        Args:
            other: Another cluster to check for overlap
            gap_tolerance: Maximum allowed gap between clusters 
                          to still consider them overlapping

        Returns:
            True if clusters overlap or are within gap_tolerance

        Examples:
            >>> c1 = Cluster((1,2,3), ('A','L','V'), 'test', 1)
            >>> c2 = Cluster((4,5), ('I','F'), 'test', 1)
            >>> c1.overlaps_with(c2, gap_tolerance=1)
            True
            >>> c1.overlaps_with(c2, gap_tolerance=0)
            False
        """
        self_min, self_max = self.min_position, self.max_position
        other_min, other_max = other.min_position, other.max_position

        return not (
                self_max + gap_tolerance < other_min or
                other_max + gap_tolerance < self_min
        )

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert to dictionary for serialization and backward compatibility.

        Returns:
            Dictionary with all cluster properties
        """
        return {
            'positions': list(self.positions),
            'residues': list(self.residues),
            'size': self.size,
            'span': self.span,
            'rule_name': self.rule_name,
            'aggregation_score': self.aggregation_score,
            'density': self.density,
            'mean_propensity': self.mean_propensity,
        }


@dataclass(frozen=True, slots=True)
class HydrophobicAromaticCluster:
    """
    Specialized cluster for hydrophobic-aromatic interaction patterns.

    Extends the standard Cluster with information about:
    - Adjacent hydrophobic-aromatic pairs
    - Nearby hydrophobic residues that stabilize interactions
    - Classification by formation mechanism

    This cluster type captures π-alkyl interactions between aromatic
    rings (F, Y, W) and aliphatic side chains (V, I, L, A, M),
    which are common in amyloid-forming sequences.

    Attributes:
        positions: 1-indexed positions of all involved residues
        residues: Amino acid codes at each position
        rule_name: Rule identifier (always 'hydrophobic_and_aromatic')
        aggregation_score: Weight for aggregation contribution
        pair_count: Number of hydrophobic-aromatic adjacent pairs
        condition: Formation mechanism ('at_least_2_pairs' or '1_pair_plus_hydrophobic')
        hydrophobic_count: Number of hydrophobic residues (V, I, L, A, M)
        aromatic_count: Number of aromatic residues (F, Y, W)
        pair_interactions: String descriptions of each pair (e.g., "V10-F11")
        nearby_hydrophobic_positions: Additional hydrophobic residues within 3 positions
    """
    positions: Tuple[int, ...]
    residues: Tuple[str, ...]
    rule_name: str
    aggregation_score: int
    pair_count: int = 0
    condition: str = ""  # 'at_least_2_pairs' or '1_pair_plus_hydrophobic'
    hydrophobic_count: int = 0
    aromatic_count: int = 0
    pair_interactions: Tuple[str, ...] = ()
    nearby_hydrophobic_positions: Tuple[int, ...] = ()

    @property
    def size(self) -> int:
        """Number of residues in the cluster."""
        return len(self.positions)

    @property
    def span(self) -> int:
        """Sequence span from first to last position (inclusive)."""
        return max(self.positions) - min(self.positions) + 1 if self.positions else 0

    @property
    def min_position(self) -> int:
        """N-terminal boundary of the cluster."""
        return min(self.positions) if self.positions else 0

    @property
    def max_position(self) -> int:
        """C-terminal boundary of the cluster."""
        return max(self.positions) if self.positions else 0

    def overlaps_with(self, other: 'Cluster', gap_tolerance: int = 0) -> bool:
        """
        Check if this cluster overlaps with another cluster.

        Args:
            other: Another cluster to check for overlap
            gap_tolerance: Maximum allowed gap between clusters

        Returns:
            True if clusters overlap or are within gap_tolerance
        """
        if not self.positions:
            return False
        self_min, self_max = self.min_position, self.max_position
        other_min, other_max = other.min_position, other.max_position
        return not (
                self_max + gap_tolerance < other_min or
                other_max + gap_tolerance < self_min
        )

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert to dictionary for serialization and output.

        Returns:
            Dictionary with all cluster properties including pair details
        """
        return {
            'positions': list(self.positions),
            'residues': list(self.residues),
            'size': self.size,
            'span': self.span,
            'rule_name': self.rule_name,
            'aggregation_score': self.aggregation_score,
            'pair_count': self.pair_count,
            'condition': self.condition,
            'hydrophobic_count': self.hydrophobic_count,
            'aromatic_count': self.aromatic_count,
            'pairs': [{'interaction': p} for p in self.pair_interactions],
            'nearby_hydrophobics': [
                {'position': p} for p in self.nearby_hydrophobic_positions
            ],
        }


@dataclass(frozen=True, slots=True)
class MultiRuleCluster:
    """
    Represents a cluster matching multiple aggregation rules simultaneously.

    These clusters indicate regions with compounded aggregation risk
    where multiple physicochemical features converge (e.g., both
    hydrophobic aliphatic and aromatic clustering in the same region).

    Multi-rule clusters receive boosted aggregation scores reflecting
    their increased risk compared to single-rule clusters.

    Attributes:
        positions: 1-indexed positions of all residues in merged cluster
        residues: Amino acid codes at each position
        rules: Tuple of rule names that converged at this region
        combined_aggregation_score: Boosted score (sum of individual scores + bonus)

    Raises:
        ValueError: If position/residue counts mismatch or fewer than 2 rules
    """
    positions: Tuple[int, ...]
    residues: Tuple[str, ...]
    rules: Tuple[str, ...]
    combined_aggregation_score: int

    def __post_init__(self):
        """Validate multi-rule cluster invariants."""
        if len(self.positions) != len(self.residues):
            raise ValueError("Position and residue counts must match")
        if len(self.rules) < 2:
            raise ValueError(
                f"MultiRuleCluster requires at least 2 rules, got {len(self.rules)}"
            )

    @property
    def size(self) -> int:
        """Number of residues in the cluster."""
        return len(self.positions)

    @property
    def span(self) -> int:
        """Sequence span from first to last position (inclusive)."""
        return max(self.positions) - min(self.positions) + 1 if self.positions else 0

    @property
    def min_position(self) -> int:
        """N-terminal boundary of the cluster."""
        return min(self.positions) if self.positions else 0

    @property
    def max_position(self) -> int:
        """C-terminal boundary of the cluster."""
        return max(self.positions) if self.positions else 0

    @property
    def is_multi_rule(self) -> bool:
        """Always True for MultiRuleCluster; aids duck typing with Cluster."""
        return True

    @property
    def rule_string(self) -> str:
        """Formatted string of all rule names joined by '+'."""
        return '+'.join(sorted(self.rules))

    @property
    def aggregation_score(self) -> int:
        """Alias for combined_aggregation_score for duck typing compatibility."""
        return self.combined_aggregation_score

    @property
    def rule_name(self) -> str:
        """Alias for rule_string for duck typing compatibility."""
        return self.rule_string

    def overlaps_with(self, other: 'Cluster', gap_tolerance: int = 0) -> bool:
        """
        Check if this multi-rule cluster overlaps with another cluster.

        Args:
            other: Another cluster to check for overlap
            gap_tolerance: Maximum allowed gap between clusters

        Returns:
            True if clusters overlap or are within gap_tolerance
        """
        if not self.positions:
            return False
        self_min, self_max = self.min_position, self.max_position
        other_min, other_max = other.min_position, other.max_position
        return not (
                self_max + gap_tolerance < other_min or
                other_max + gap_tolerance < self_min
        )

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert to dictionary for serialization.

        Returns:
            Dictionary with all multi-rule cluster properties
        """
        return {
            'positions': list(self.positions),
            'residues': list(self.residues),
            'size': self.size,
            'span': self.span,
            'rules': list(self.rules),
            'combined_aggregation_score': self.combined_aggregation_score,
            'is_multi_rule': True,
        }


# Type alias for any cluster type
ClusterType = Union[Cluster, HydrophobicAromaticCluster, MultiRuleCluster]


# =============================================================================
# POSITION AND MUTATION DATA CLASSES
# =============================================================================

@dataclass
class PositionContext:
    """
    Structural context of a sequence position relative to aggregation-prone regions.

    Classifies each position by its distance to the nearest identified
    aggregation cluster, enabling targeted mutagenesis strategies.

    Terminology:
    - APR: Aggregation-Prone Region (identified by clustering rules)
    - Gatekeeper: Position at/near APR boundary where mutations can disrupt β-extension
    - Flanking: Beyond gatekeeper zone but still near APR
    - Core: Within the APR cluster itself

    Attributes:
        position: 1-indexed sequence position
        context_type: Classification of this position's structural context
        distance_to_nearest_apr: Number of residues to nearest APR boundary (0 if within)
        nearest_apr_boundary: Position of the closest APR boundary residue
        apr_id: Index of the nearest APR in the clusters list
    """
    position: int
    context_type: MutationType
    distance_to_nearest_apr: int
    nearest_apr_boundary: Optional[int] = None
    apr_id: Optional[int] = None


@dataclass
class MutationInfo:
    """
    Structured representation of a single mutation with full biological context.

    Encapsulates all information about a mutation including its structural
    context (gatekeeper, core, flanking), aggregation impact, and
    the rule(s) that triggered it.

    Attributes:
        position: 1-indexed position in the sequence
        original_aa: Single-letter code of the original amino acid
        new_aa: Single-letter code of the new amino acid
        mutation_type: Classification of the mutation's structural context
        aggregation_score: Impact score for aggregation propensity
        region: Optional region string (format: "start:stop")
        rule_name: Name of the rule that triggered this mutation
        distance_to_apr_boundary: Distance to nearest APR boundary
        sequence: The full mutated sequence
        description: Formatted description string for FASTA output
    """
    position: int
    original_aa: str
    new_aa: str
    mutation_type: MutationType
    aggregation_score: int
    region: Optional[str] = None
    rule_name: Optional[str] = None
    distance_to_apr_boundary: Optional[int] = None
    sequence: str = ""
    description: str = ""

    @property
    def is_gatekeeper(self) -> bool:
        """Check if this mutation is at a gatekeeper position."""
        return self.mutation_type == MutationType.GATEKEEPER

    @property
    def is_core(self) -> bool:
        """Check if this mutation is within an APR core."""
        return self.mutation_type == MutationType.BETA_CORE

    def to_tuple(self) -> Tuple[str, str, int]:
        """
        Convert to legacy tuple format for backward compatibility.

        Returns:
            Tuple of (description, sequence, aggregation_score)
        """
        return (self.description, self.sequence, self.aggregation_score)


@dataclass
class MultiMutationResult:
    """
    Structured result for multi-point mutation combinations.

    Represents a sequence variant with mutations at multiple positions,
    including classification of the combined mutation types and regions.

    Attributes:
        description: Formatted description for FASTA header
        sequence: Full mutated sequence with all changes applied
        aggregation_score: Combined aggregation impact score
        positions: List of mutated positions
        regions: List of region strings involved
        level: Number of simultaneous mutations (2=double, 3=triple, etc.)
        mutation_types: Tuple of MutationType for each position
        type_composition: Tuple of type name strings
        original_aas: Original amino acids at each position
        new_aas: New amino acids at each position
    """
    description: str
    sequence: str
    aggregation_score: int
    positions: List[int]
    regions: List[str]
    level: int
    mutation_types: Tuple[MutationType, ...]
    type_composition: Tuple[str, ...]
    original_aas: Tuple[str, ...] = ()
    new_aas: Tuple[str, ...] = ()

    @property
    def is_all_gatekeeper(self) -> bool:
        """Check if all component mutations are gatekeepers."""
        return all(mt == MutationType.GATEKEEPER for mt in self.mutation_types)

    @property
    def is_all_core(self) -> bool:
        """Check if all component mutations are in β-core regions."""
        return all(mt == MutationType.BETA_CORE for mt in self.mutation_types)

    @property
    def is_mixed(self) -> bool:
        """Check if mutations span different structural contexts."""
        return len(set(self.mutation_types)) > 1

    @property
    def is_single_region(self) -> bool:
        """Check if all mutations are in the same region."""
        return len(set(self.regions)) <= 1

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert to dictionary for serialization and output.

        Returns:
            Dictionary with all multi-mutation properties
        """
        return {
            'description': self.description,
            'sequence': self.sequence,
            'agg_score': self.aggregation_score,
            'positions': self.positions,
            'regions': self.regions,
            'level': self.level,
            'mutation_types': self.mutation_types,
            'type_composition': self.type_composition,
            'is_all_gatekeeper': self.is_all_gatekeeper,
            'is_all_core': self.is_all_core,
            'is_mixed': self.is_mixed,
        }

    def to_tuple(self) -> Tuple[str, str, int]:
        """
        Convert to legacy tuple format (description, sequence, score).

        Returns:
            Tuple of (description, sequence, aggregation_score)
        """
        return (self.description, self.sequence, self.aggregation_score)